### ISSUE TITLE
bash-preexec

### ISSUE THREAD

**Issue by D630** [rcaloras/bash-preexec#1]
Hey,

I have forked your project and modified it to my needs. Have a look at [it](https://github.com/D630/bpx), if you like.

Cheers

**Comment by rcaloras** [comment]
Cool man, any particular reason for the fork? I'm interested in trying to address use cases that my current implementation may not support. Not to mention bugs :) Thanks for your interest!

**Comment by D630** [comment]
Ja, there were two reasons:
- I have removed the sed scripts and (the very smart!) invocation/use of `__bp_trim_whitespace()` in `__bp_precmd_invoke_cmd()` to speed up the thing a bit
- access to `$?` in the `precmd` mechanism. Currently, I am using it like [this](https://github.com/D630/stow-dot-pub/blob/master/bash/.bashrc.d/11-prompt.sh)

In my last commit, preexecution is beeing allowed, even though history has been disabled

**Comment by rcaloras** [comment]
Yeah the use of sed to save the previous prompt command and the trimming is all stuff that is a little heavy. I actually just needed to get access to ```$?``` as well so I wrote 417c01bba263e54084a1ff2028e0de to sort of simulate it. 

Thanks for your feedback and input. Feel free to open anything or put in a pull request if you want to make changes.

**Comment by D630** [comment]
Thanks!
