### ISSUE TITLE
It's possible to prevent the execution of the command?

### ISSUE THREAD

**Issue by diegobernardes** [rcaloras/bash-preexec#105]
I'm looking for a way to use the `preexec` to do some validation and be able to prevent the actual command from being executed.
It's possible to do this?

**Comment by rcaloras** [comment]
Hey @diegobernardes, don't believe this is currently possible. While you could validate or do operations prior to the command being executed, not sure you could then stop its actual execution. One of the contributors more familiar with bash might have a suggestion though or a way cc @d630

**Comment by dimo414** [comment]
According to [this comment](https://github.com/rcaloras/bash-preexec/blob/f558191/bash-preexec.sh#L242) `preexec` respects the [`extdebug` option](https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html), which causes "the next command [to be] skipped and not executed" if the `DEBUG` command returns a non-zero value.

So it should be possible as long as using `extdebug` is acceptable (but note this changes a number of behaviors of the shell, so you probably don't want to just enable it globally). Without `extdebug` I imagine this isn't possible, as @rcaloras said.

**Comment by dimo414** [comment]
Looks like it works:

```shell
$ source bash-preexec.sh
$ preexec() { echo PREEXEC; return 1; }

# By default execution proceeds
$ echo CMD
PREEXEC
CMD

$ shopt -s extdebug
PREEXEC

# now echo is skipped
$ echo CMD
PREEXEC

# Fortunately(?) DEBUG doesn't fire on function (re)definitions
$ preexec() { echo PREEXEC; }

# Now execution can proceed
$ echo CMD
PREEXEC
CMD
```

**Comment by rcaloras** [comment]
@dimo414 thanks for chiming in! Forgot about this :) 
> So it should be possible as long as using extdebug is acceptable (but note this changes a number of behaviors of the shell, so you probably don't want to just enable it globally)

Want to underscore this point as my guess is this might make it not a viable solution for @diegobernardes. Closing this issue, feel free to reopen if needed!
