### ISSUE TITLE
fc prints debug trap

### ISSUE THREAD

**Issue by gnachman** [rcaloras/bash-preexec#108]
The bash builtin `fc` opens your editor and lets you edit the command line. Upon saving and exiting the editor, bash prints the debug trap (which is `__bp_preexec_invoke_exec` when bash-preexec is installed); then it prints the command to stdout, and then runs the command. This is a bug in bash, as discussed here:

https://lists.gnu.org/archive/html/bug-bash/2020-04/msg00016.html

It'll probably be a long time before this fix is widely deployed as bash releases are infrequent. I came up with a workaround, but I am a bash dilettante at best, so take this with a grain of salt:

```
__bp_fc() {
 trap - DEBUG
 command fc "$@"
 trap -- '__bp_preexec_invoke_exec "$_"' DEBUG
}
alias fc=__bp_fc
```

Is this something that should be part of bash-preexec?

**Comment by dimo414** [comment]
It doesn't really seem like it should be part of bash-preeexec to me, is there a particular reason you think it should?

**Comment by gnachman** [comment]
It's pretty ugly see `__bp_preexec_invoke_exec` printed every time you use `fc`. In vi mode, it's the `v` command; in emacs mode it's C-x C-e.  The reason I think it might belong in bash-preexec is that bash-preexec is triggering a bug in bash which could be worked around. I think the bgest counterargument is that bash ought to fix their bug instead of accruing technical debt to bash-preexec. But bash's release cycle is preposterously long (like a decade for long-term support distros), so that should be taken into account.

**Comment by d630** [comment]
Hm. You might also use your own binding to `v`  and `C-x C-e`! :roll_eyes: 

One without fc (which sets `set -v`)

**Comment by dimo414** [comment]
I agree the DEBUG trap being printed by `set -v` is noisy, but it seems like intentional behavior (prior to the change made in the linked thread), and isn't specific to bash-preexec.

The proposal to disable the DEBUG trap prior to running a command seems at odds with the purpose of bash-preexec, and seems (to me) like a worse behavior than spurious output.

```shell
bash-5.0$ EDITOR='ed -s'
bash-5.0$ debugTrap() { printf 'DEBUG trap fired!\n\t%s\n' "$(builtin history 1)"; }
bash-5.0$ trap -- debugTrap DEBUG

# DEBUG trap fires as-expected
bash-5.0$ echo foo
DEBUG trap fired!
	  502  echo foo
foo

# But with fc it fires _three_ times, the last of which is the command
# that's actually run (I'm curious why it fires the second time, maybe
# that's also unintended behavior?)
bash-5.0$ fc <<<$'s/foo/bar/\nw'
DEBUG trap fired!
	  503  fc <<<$'s/foo/bar/\nw'
DEBUG trap fired!
	  502  echo foo
echo bar
debugTrap
DEBUG trap fired!
	  503  echo bar
bar

# Suppressing the DEBUG trap from fc means the debug trap doesn't
# fire only for the initial fc command, not at "preexec" time, and the
# actual command that will run isn't known yet
bash-5.0$ fc() { trap - DEBUG; command fc "$@"; trap -- debugTrap DEBUG; }
bash-5.0$ echo biff
DEBUG trap fired!
	  505  echo biff
biff
bash-5.0$ fc <<<$'s/biff/bang/\nw'
DEBUG trap fired!
	  506  fc <<<$'s/biff/bang/\nw'
echo bang
bang
```

Not to mention that `fc` isn't the only way to trigger this; as @d630 points out using `C-x C-e` will also cause the debug trap to be printed, and wrapping `fc` won't help with that.

**Comment by gnachman** [comment]
For me aliasing fc does affect C-x C-e. But you're right: if it doesn't fire for the command entered from fc's editor then it's a no-go. I think we'll have to wait for bash to release their fix. Sorry for the wild goose chase!

**Comment by d630** [comment]
```
$ PROMPT_COMMAND=; FCEDIT=cat; debugTrap() { printf 'DEBUG trap fired!\n\t%s\n' "$BASH_COMMAND"; }; trap -- debugTrap DEBUG
$ echo foo
DEBUG trap fired!
    echo foo
foo
$ fc <<< ''
DEBUG trap fired!
    fc <<< ''
DEBUG trap fired!
    ${FCEDIT:-${EDITOR:-$(command -v editor || echo vi)}} /tmp/user/1000/bash-fc.tIYJ0r
echo foo
echo foo
debugTrap
DEBUG trap fired!
    echo foo
foo
```
