### ISSUE TITLE
Is it possible to capture the output of a shell command?

### ISSUE THREAD

**Issue by karlgodard** [rcaloras/bash-preexec#11]
i.e if I type "ls", can something be done in bash-preexec.sh to feed the ouput of "ls" into the invocation of precmd?

**Comment by rcaloras** [comment]
Howdy,

I've been considering something like this for [Bashhub](https://github.com/rcaloras/bashhub-client). Probably doesn't make sense for bash-preexec to do it as this is just supposed to be a plugin/addon to provide Zsh type functionality for Bash. I have come across some hacks to do what you want though, check out http://stackoverflow.com/a/6052267/1282124.

If you have some luck connecting it with bash-preexec let me know! I'll probably add it to Bashhub at some point.
