### ISSUE TITLE
Line number exit outpu command ?

### ISSUE THREAD

**Issue by gpxlnx** [rcaloras/bash-preexec#126]
Hey guys,

Is there any way to display, for example, the number of lines in the output of a command?

Ex.

$ ls
1 file1
2 arch2
3 arch3

**Comment by dimo414** [comment]
There's the [`nl`](https://manpages.debian.org/nl) command, or equivalently a custom bit of Bash could do the same in a few lines, but I don't think there's any way to hook into the pipeline like this at the time(s) bash-preexec is running without somehow modifying the command itself.
