### ISSUE TITLE
Functions called in opposite order in midnight commander subshell

### ISSUE THREAD

**Issue by josef-kyrian** [rcaloras/bash-preexec#140]
I have defined simple functions for test and added to .bashrc. They print command to run and it's return code
```bash
preexec() { echo "RUN: $1"; }
precmd() { echo "EXIT: $?"; }
source ~/.bash-preexec.sh
```

In bash shell it's working ok:
```
# ls /
RUN: ls /
bin  boot  cdrom  dev  etc  home  initrd.img  lib  lib32  lib64  lxc  media  mnt  opt  proc  root  run  sbin  snap  srv  sys  tmp  usr  var  vmlinuz  www
EXIT: 0
```

But in midnight commander subshell functions are called in opposite order
```
# ls /
bin  boot  cdrom  dev  etc  home  initrd.img  lib  lib32  lib64  lxc  media  mnt  opt  proc  root  run  sbin  snap  srv  sys  tmp  usr  var  vmlinuz  www
EXIT: 0
RUN: ls /
```

What's wrong? Thanks for help

**Comment by akinomyoga** [comment]
`bash-preexec` doesn't support the case where `PROMPT_COMMAND` is modified after the shell startup and the first prompt. However, Midnight Commander installs its hook by *directly inputting `PROMPT_COMMAND+=...`, etc. as user commands* from stdin after starting the shell.

More specifically, `bash-preexec` requires that all the other `PROMPT_COMMAND` hooks are enclosed between `__bp_precmd_invoke_cmd` and `__bp_interactive_mode`. This is normally achieved through the initial `DEBUG` trap (`__bp_install`) installed by `bash-preexec`. However, Midnight Commander injects codes after the shell startup and modifies `PROMPT_COMMAND`. This results in the following value of `PROMPT_COMMAND`:

```bash
$ declare -p PROMPT_COMMAND
declare -- PROMPT_COMMAND=$'__bp_precmd_invoke_cmd\n__bp_interactive_mode\npwd>&11;kill -STOP $$'
```

The substring `pwd>&11;kill -STOP $$` is the hook installed by `mc`. We can see that the `mc` hook string is not enclosed within `__bp_precmd_invoke_cmd` and `__bp_interactive_mode`. Instead, this should look like the following:

```bash
PROMPT_COMMAND=$'__bp_precmd_invoke_cmd\npwd>&11;kill -STOP $$\n__bp_interactive_mode'
```

I'm not sure if there is a solution at the user side.
