### ISSUE TITLE
preexec() does not work where as precmd() is working as intended.

### ISSUE THREAD

**Issue by NikhilBayyavarapu** [rcaloras/bash-preexec#145]
Using Pop OS,  bash version 5.1.16(1)-release (x86_64-pc-linux-gnu)

1) Cloned the repo.
2) Sourced the bash-preexec.sh file.
3) Defined the preexec() and precmd() functions.

precmd() is working where as preexec() doesn't work.
Even tried enabling the subshell support variable.

Did not source the contents of bash-preexec.sh file into my .bashrc as I just wanted to test this out.

Edit : Working fine now. Fig was causing the issue. Uninstalled fig and preexec() is now working fine. Thanks.

**Comment by dimo414** [comment]
If you're using Fig (i.e. you're at Google) bash-preexec is likely already installed in your system by default. The issue might have been that you were installing it a second time and overwriting the existing script and functions. Better to use the [function arrays](https://github.com/rcaloras/bash-preexec#function-arrays) in any case.
