### ISSUE TITLE
Remove subshells and external commands (= sed)

### ISSUE THREAD

**Issue by D630** [rcaloras/bash-preexec#17]
Hi,

I have opened four pull requests. Don't know, whether they are compatible with Bash on BSD

#13, #14, #15, #16

**Comment by rcaloras** [comment]
Hey @D630!

Thanks for the contributions, I'll give them a look over the next day and pull them in. What would you say are the major benefits of removing the subshells and sed? Simplicity, portability, speed? 

Appreciate it :+1:

**Comment by D630** [comment]
Hey!

It is unnecessary to use sed, because bash can do the job itself (and in the end even faster). Command substitutions are only necessary, if we do need the output of a command. But in #15 and #16 it is sufficient to work with exit/return status. See also [SubShell](http://mywiki.wooledge.org/SubShell).

So, the major benefits are simplicity and speed

**Comment by rcaloras** [comment]
Thank you for the contributions @D630! Much appreciated. :+1: 

Would love your feedback or input on my project [Bashhub](https://github.com/rcaloras/bashhub-client) which uses bash-preexec if you're interested.
