### ISSUE TITLE
preexec breaks passed-in environment variables when used with command builtin

### ISSUE THREAD

**Issue by gnachman** [rcaloras/bash-preexec#19]
I received this bug report for my script which uses the same trickery as bash-preexec:

https://gitlab.com/gnachman/iterm2/issues/3644

It seems that setting a DEBUG trap breaks this use case:

```
FOO=BAR command something_that_uses_foo.sh
```

To reproduce with bash-preexec:

```
echo 'echo $BUILD_SYSTEM' > p
chmod +x p

# Note that this prints "build/core"
BUILD_SYSTEM=build/core command ./p

# Now set up preexec and notice that it breaks
source ~/.bash-preexec.sh
function preexec() {
true
}

# This produces no output
BUILD_SYSTEM=build/core command ./p
```

This is a problem because it means preexec is incompatible with building Android, and who knows what else. Seems like a bug in bash, but I'm not much of a bash expert myself.

**Comment by rcaloras** [comment]
@gnachman Thanks for reporting! I'll give this a look over the weekend and see if I can find a workaround.

**Comment by potiuk** [comment]
Had the same problem. It's pretty annoying but seems it's a very isolated problem, that at least until this is fixed, has a simple workaround for Android build. This will at least let Android builders use the goodies of @gnachman's iTerm2 shell integration, which is brilliant :)

Patch for build directory of android

```
diff --git a/envsetup.sh b/envsetup.sh
index 776ebaa..caa6708 100644
--- a/envsetup.sh
+++ b/envsetup.sh
@@ -37,7 +37,7 @@ function get_abs_build_var()
         echo "Couldn't locate the top of the tree.  Try setting TOP." >&2
         return
     fi
-    (\cd $T; CALLED_FROM_SETUP=true BUILD_SYSTEM=build/core \
+    (\cd $T; export CALLED_FROM_SETUP=true BUILD_SYSTEM=build/core; \
       command make --no-print-directory -f build/core/config.mk dumpvar-abs-$1)
 }
 
@@ -49,7 +49,7 @@ function get_build_var()
         echo "Couldn't locate the top of the tree.  Try setting TOP." >&2
         return
     fi
-    (\cd $T; CALLED_FROM_SETUP=true BUILD_SYSTEM=build/core \
+    (\cd $T; export CALLED_FROM_SETUP=true BUILD_SYSTEM=build/core; \
       command make --no-print-directory -f build/core/config.mk dumpvar-$1)
 }
 ```

**Comment by naseer** [comment]
Can you please submit this on the AOSP gerrit?

**Comment by potiuk** [comment]
Will do :)
