### ISSUE TITLE
How is this different than Glyph Lefkowitz’s original version?

### ISSUE THREAD

**Issue by exalted** [rcaloras/bash-preexec#2]
Just for curiosity, I wanted to know how is this different than [Glyph Lefkowitz’s original version](http://www.twistedmatrix.com/users/glyph/preexec.bash.txt) please?

Thanks.

**Comment by rcaloras** [comment]
Howdy,

The largest is it's more similar to zsh by providing function arrays to hook multiple functions for pre and post cmd execution (detailed in the readme!) and preserving things like the return value of the last command. In general though, it's more robust and actually packaged for reuse. There are a lot of small things and edge cases I covered like:

*  Multiple Inclusion
```bash
# Avoid duplicate inclusion
if [[ "$__bp_imported" == "defined" ]]; then
    return 0
fi
__bp_imported="defined"
```
*  Name spacing `__bp`
*  Error checking
```bash
 # Only execute this function if it actually exists.
        if [[ -n $(type -t $precmd_function) ]]; then
            __bp_set_ret_value $ret_value
            $precmd_function
        fi
```
* Preserving the existing PROMPT_COMMAND
```bash
 # Take our existing prompt command and append a semicolon to it
    # if it doesn't already have one.
    local existing_prompt_command

    if [ -n "$PROMPT_COMMAND" ]; then
        existing_prompt_command=$(echo "$PROMPT_COMMAND" | sed '/; *$/!s/$/;/')
    else
        existing_prompt_command=""
    fi
```
*  There's a slew of others as well :)

I use this project in production for my current side project https://github.com/rcaloras/bashhub-client which I have a growing user base for. Glyph's code is a hack which I initially templated, but I didn't want to use his stuff in production. So I improved upon it and I'm fairly happy with the result so far. 

Please try it out and let me know your feedback!

**Comment by rcaloras** [comment]
Feel free to post any other questions. Thanks!

**Comment by exalted** [comment]
@rcaloras sorry for being such a lazy *ss! Thanks for detailed explanation. I will see how can I make it work in my own use case and eventually report back if things make sense.

Cheers!
