### ISSUE TITLE
Incompatibility with "z"

### ISSUE THREAD

**Issue by shpoont** [rcaloras/bash-preexec#20]
Steps to reproduce:
1. Install "z" from https://github.com/rupa/z
2. Source "z" before "bash-preexec"
3. Start new shell session

Actual result: 
1. The precmd function is executed
2. The preexec function is executed with last command from history

Expected result: 
1. The precmd function is executed

**Comment by rcaloras** [comment]
@shpoont thanks for opening the issue and using bash-preexec! Noticed you added it to [brew](https://github.com/Homebrew/homebrew/commit/3c81f48b174375db5cd50a7669305bcefe429aad) and used it as a requirement for your project :D

I'm unable to reproduce this issue with master, so maybe it's due to bugs in v2.2. I'll cut 2.3 for you now.

**Comment by rcaloras** [comment]
Just cut `0.2.3` can you give that a try and see if that's working?

**Comment by shpoont** [comment]
Hi, I still have the same problem on 0.2.3

**Comment by rcaloras** [comment]
I'm unable to reproduce on OS X or Linux. Bash Versions 3.2 and 4.3 respectively.

`~/.bash_profile` looks like:
```bash
source ~/git/z/z.sh
source ~/git/bash-preexec/bash-preexec.sh

preexec() { echo "just typed $1"; }
precmd() { echo "printing the prompt"; }
```
Opening a new terminal window:
```bash
Last login: Sun Dec  6 19:08:06 on ttys006
printing the prompt
19:11:13-rcaloras-~/git/z (master)$ 
```
`PROMPT_COMMAND` looks like this:
```bash
19:12:00-rcaloras-~/git/z (master)$ echo "$PROMPT_COMMAND"
__bp_precmd_invoke_cmd; update_terminal_cwd; 
_z --add "$(command pwd -P 2>/dev/null)" 2>/dev/null; __bp_interactive_mode;
```
What's your `PROMPT_COMMAND` look like?

**Comment by rcaloras** [comment]
Alternatively _z could be invoked via `precmd()` or `preexec()` which would avoid empty returns.

**Comment by rcaloras** [comment]
FYI there was a similar issue a little while back, but it was just a sourcing problem. So some other folks have been able to use these together successfully :) https://github.com/rcaloras/bash-preexec/issues/4

**Comment by rcaloras** [comment]
Perhaps bash-preexec is not the last thing sourced in your config file. `__bp_interactive_mode` needs to be the last thing in your `PROMPT_COMMAND`

**Comment by rcaloras** [comment]
@shpoont any luck?

**Comment by shpoont** [comment]
Hey @rcaloras I just checked again and it looks to be ok with the latest version. Also I am able to run powerline after bash-preexec and it works fine, just fyi ;)

Thanks for your help!

**Comment by rcaloras** [comment]
@shpoont great good to hear!
