### ISSUE TITLE
Conflicts with iTerm2 shell integration.

### ISSUE THREAD

**Issue by rcaloras** [rcaloras/bash-preexec#21]
Causes: https://github.com/rcaloras/bashhub-client/issues/27

Looks like both projects leverage the debug trap to create a preexec function. @gnachman any chance you could be convinced to use this library if it can provide everything you need for iTerm2's preexec functionality? I'm happy to make all the PRs :) I want to make sure Bashhub and iTerm2 can work together. 

*Quoted from* https://github.com/rcaloras/bash-preexec/issues/6

*I'd love to fix up this project to make it compatible with the awesome iTerm2 :) I wrote bash-preexec to include [function arrays ](https://github.com/rcaloras/bash-preexec#function-arrays) and to avoid multiple inclusion which allows multiple shell integrations to add preexec functions triggered through one debug trap hook. Any chance you'd be willing to switch to this library if I make it compatible?*

Thanks!

**Comment by gnachman** [comment]
See my comment in #6

**Comment by rcaloras** [comment]
Fixed in 0.3.0.
