### ISSUE TITLE
Cannot get true exit status

### ISSUE THREAD

**Issue by kylebrowning** [rcaloras/bash-preexec#24]
I run lots of scripts so Ive been wanting bash to update some things once its done.

doing a `precmd() { updatestatus -green; echo $?; }; `

shows that Bash exit status is 0, even if I type `false`

```
bash-3.2$ false
0
```

**Comment by rcaloras** [comment]
@kylebrowning I think $? is picking up the exit status of the command before it `updatestatus`. If you want to use the exit status you should save it as the first command in your precmd function.

```bash
16:53:39-rcaloras-~/git/bash-preexec (master)$ precmd() { echo "$?"; }
0
16:53:46-rcaloras-~/git/bash-preexec (master)$ false
1
```
Let me know if it's still an issue!

**Comment by rcaloras** [comment]
@kylebrowning all good?

**Comment by kylebrowning** [comment]
Yup!
