### ISSUE TITLE
Doesn't actually work at all

### ISSUE THREAD

**Issue by Integralist** [rcaloras/bash-preexec#29]
```bash
$ source .bash-preexec.sh
$ preexec() { echo "just typed $1"; }
$ date

Fri Oct  7 11:42:38 BST 2016
```

Here is my Bash version (installed via Homebrew):

```bash
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.4.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Here is the bash location:

```bash
/usr/local/bin/bash
```

**Comment by rcaloras** [comment]
@Integralist thanks for opening. Could you provide a bit more debugging information after you've sourced bash-preexec.sh?

```bash
# Contents of your prompt command
echo $PROMPT_COMMAND 
# Contents of preexec 
echo ${preexec_functions[@]}
# Contents of precmd
echo ${precmd_functions[@]}
# Trap should contain bash-preexec's hook
trap
# Check if it's imported
echo "$__bp_imported"
```
Should return values like..
```bash
$ echo $PROMPT_COMMAND 
__bp_precmd_invoke_cmd; __bp_interactive_mode;
$ echo ${preexec_functions[@]}
__bh_preexec preexec
$ echo ${precmd_functions[@]}
__bh_precmd_run_script __bh_bash_precmd __bh_precmd precmd
$ trap 
trap -- '' SIGTSTP
trap -- '' SIGTTIN
trap -- '' SIGTTOU
trap -- '__bp_preexec_invoke_exec' DEBUG    
$ echo $__bp_imported 
defined
```

Not sure about the homebrew installation, as I didn't create it or use it, but my guess is something is conflicting with your trap or PROMPT_COMMAND.

**Comment by Integralist** [comment]
Sure thing @rcaloras the details you've asked for are as follows...

> btw, here is my [~/.bashrc](https://github.com/Integralist/dotfiles/blob/master/.bashrc) file. I found if I move the sourcing of the file to the bottom of that (rather than doing it at the top) I would get _some_ output, but it seemed a bit inconsistent. It might be my crazy prompt code I've got going on that's messing something up

```bash
$ echo $PROMPT_COMMAND
history -a

$ echo ${preexec_functions[@]}
preexec

$ echo ${precmd_functions[@]}
precmd

$ trap
trap -- 'shell_session_update' EXIT
trap -- '' SIGTSTP
trap -- '' SIGTTIN
trap -- '' SIGTTOU
trap -- '__bp_preexec_invoke_exec' DEBUG

$ echo "$__bp_imported"
defined
```

**Comment by rcaloras** [comment]
So it looks like bash-preexec is getting pulled in correctly, but PROMPT_COMMAND is not right. If it's right, your PROMPT_COMMAND should have at least the two functions mine does:

```bash
$ echo $PROMPT_COMMAND 
__bp_precmd_invoke_cmd; __bp_interactive_mode;
```

Looking at your ~/.bashrc, it looks like you're overwriting PROMPT_COMMAND in a few places. From your file:

```bash
export PROMPT_COMMAND='history -a' # record each line as it gets issued

# override builtin cd so it resets command prompt when changing directories
function cd {
  builtin cd "$@"
  RET=$?

  PROMPT_COMMAND=prompt

  # Disabled following because it seems to be pointless now?
  # That or I just don't know what it was really doing originally?
  #
  # # After each command, append to the history file and reread it...
  # export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

  return $RET
}
```

One thing you could do is remove the overwriting of PROMPT_COMMAND and instead define whatever you want in PROMPT_COMMAND as part of a precmd function e.g.

```bash
precmd() {
history -a
}
```

Give it a shot. Let me know if there's anything else I can help with.

**Comment by Integralist** [comment]
Heya, so I've got this working now. Totally my bad.

I sorted out my command prompt setup and it works fine 👍 

Thanks for taking the time to look into this, you were right `PROMPT_COMMAND` was getting messed around with when it didn't need to be now I'm using your script

**Comment by rcaloras** [comment]
@Integralist no worries! Glad you got it working and I could help! Feel free to checkout some of my other projects as well, bash-preexec was designed to power https://bashhub.com.
