### ISSUE TITLE
Preexec before SSH command

### ISSUE THREAD

**Issue by vroumvroum** [rcaloras/bash-preexec#31]
Hello,

I'm trying to change my tmux window name on the fly when i'm connecting to another server through SSH.
I tried the following : 

`preexec() { if [ "$1" == "ssh" ]; then tmux rename-window $3@$1; else tmux rename-window $(whoami)@$(hostname); fi }`

After trying `ssh myhost -l myuser`
Preexec does not seem to be executed ...

Am i missing something ?

Thank you, regards, Greg.

**Comment by rcaloras** [comment]
Hey @vroumvroum,

I'm unable to recreate. Could you try using a simpler preexec command? e.g. 

```bash
preexec() { echo "«$1»"; }
```

**Comment by vroumvroum** [comment]
Hey @rcaloras,

Thank you so much for answering.
It's working now. I didn't understand that command line arguments was all aggregated into "$1".

So I needed to cut "$1" or make a regex search on it. Here is what I did

```
preexec() { cmd=$(echo $1 | cut -d " " -f1); if [ "$cmd" == "ssh" ]; then tmux rename-window "$1"; fi }
precmd() { tmux rename-window "vroumvroum VDI"; }
```
Regards, Greg.

**Comment by rcaloras** [comment]
Great. Glad to hear everything is good. Thanks for using bash-preexec!
