### ISSUE TITLE
Is it possible to define preexec and precmd function just for a specific script ?

### ISSUE THREAD

**Issue by CaptainQuirk** [rcaloras/bash-preexec#33]
Hi there !

I was just wondering if it was possible to define preexec and precmd functions inside a script so that any information gathered there can be used in a local context.

Thanks in advance

**Comment by rcaloras** [comment]
Hey @CaptainQuirk! Not sure I understand your question exactly, but you can't define preexec and precmd functions for scripts. The function will only work for commands run interactively from the terminal..

**Comment by rcaloras** [comment]
@CaptainQuirk closing this, feel free to reopen if needed!
