### ISSUE TITLE
[question] Modify command before invocation (but add an unmodified one to history)

### ISSUE THREAD

**Issue by beyondcompute** [rcaloras/bash-preexec#34]
Hello and thank you for you terrifically useful project! 🙂 
One simple question regarding usage. Is it possible to do something with the command entered (`$1` in `preexec` function) before it gets executed by the shell? My practical interest is to append `time` to every command, for example.
Thank you for your response in advance and have a good week!

**Comment by rcaloras** [comment]
@beyondcompute Thanks!
Don't think you can modify the command that is about to be executed, but you can modify the environment. e.g. Set variables which can be used after the fact. You can use that to do the same thing as `time` to track the duration of a command. There's a handful of libraries where people do this and place it in their prompt I believe.

In any of the examples, just swap the preexec and precmd function for anything referencing `trap` and `PROMPT_COMMAND`.
 
Once such example: http://stackoverflow.com/a/1862762

**Comment by rcaloras** [comment]
@beyondcompute feel free to reopen if you have any other questions 👍

**Comment by beyondcompute** [comment]
Thanks a lot, @rcaloras! 🥇 I really appreciate your help!
