### ISSUE TITLE
injecting preexec function name into terminal when using editor

### ISSUE THREAD

**Issue by CeleritasCelery** [rcaloras/bash-preexec#36]
When editing a Bash command you can use `Ctrl-x Ctrl-e` to open the command in `$EDITOR`, which I have set to Vim. Once I am doing editing the command, i execute `:wq` to quit Vim and when I look at my terminal I see `__bp_preexec_invoke_exec` being injected into the output.

So for example if I create the command `echo foo` in vim then ran it, my output would look like 
```
> echo foo
__bp_preexec_invoke_exec
foo
```

Any idea why this might be happening and is there a fix?

I am using bash 4.4

**Comment by D630** [comment]
Maybe you can define a preexec function with something like `echo "$BASH_COMMAND"` to see what is beeing executed by "edit-and-execute-command".

I get the follwowing:
```sh
fc -e "${VISUAL:-${EDITOR:-$(command -v editor || echo emacs)}}"
/usr/bin/vim /run/user/1000/tmp/bash-fc.IUxsw9
```

**Comment by CeleritasCelery** [comment]
when I use set -v I get and try the command `echo foo`
```
fc -e "${VISUAL:-${EDITOR:-emacs}}"
__bp_preexec_invoke_exec
vim /tmp/bash-fc-9053782316985282392
__bp_preexec_invoke_exec
echo foo
__bp_preexec_invoke_exec
foo
```

Does it not inject the function into the output for you?

**Comment by rcaloras** [comment]
@CeleritasCelery Yes. I'm getting the same output as in your top example. Wondering what's causing it in bash-preexec.

**Comment by dschep** [comment]
I've noticed this behavior for a while but I just ignore it :stuck_out_tongue:

**Comment by rcaloras** [comment]
I'm not positive there's anything that can be done about this since bash-preexec relies on bash's `DEBUG` trap.

Even setting a no-op here will be echoed out. Using your example from above @CeleritasCelery  e.g.
```bash
$ trap -- ':' DEBUG
Ctrl-x Ctrl-e
echo foo
:
foo
```

**Comment by rcaloras** [comment]
@CeleritasCelery unfortunately this is a product of using the `DEBUG` trap which is pretty much a must.
@D630 any idea why edit and execute pulls in the contents of the trap?

**Comment by D630** [comment]
@rcaloras It's not because of Readline's "edit-and-execute-command", it's due to fc, that
sets the verbose flag before executing the file. See
http://git.savannah.gnu.org/cgit/bash.git/tree/builtins/fc.def?h=devel

I suppose you can avoid it, if you bind your own "edit-and-execute-command" ...

**Comment by rcaloras** [comment]
@D630 Thanks! Looking back at your previous comment more closely makes sense now :+1: 
@CeleritasCelery Sorry for the verbose output, but closing this as this is intended functionality by edit and execute.

**Comment by CeleritasCelery** [comment]
thanks for looking into it
