### ISSUE TITLE
Can I completely abort command execution?

### ISSUE THREAD

**Issue by frozenminds** [rcaloras/bash-preexec#37]
Hello,

I'm trying to write a helper for certain commands in `preexec`, but when certain conditions are met I'd like to completely abort execution of the command.

Is this possible?

Thank you in advance!

**Comment by brandonweeks** [comment]
I added this functionality in #35.

**Comment by rcaloras** [comment]
@frozenminds thanks for opening. I'm not positive off hand how you'd do this, but @brandonweeks might have some idea. Perhaps via `extdebug` as was mentioned in the previous PR.

**Comment by richard-scott** [comment]
Maybe this will help:

```
$ source ~/.bash-preexec.sh
$ precmd() { echo "printing the prompt"; }
$ preexec() { if [[ $SKIP = "true" ]]; then return 1; fi; }
printing the prompt
$ shopt -s extdebug
printing the prompt
$ echo 1
1
printing the prompt
$ SKIP=true
printing the prompt
$ echo 1
printing the prompt
$
```

**Comment by richard-scott** [comment]
LOL looking back, that may be a bad example as it then renders that bash session useless as you can't unset SKIP to be false ;-(

Using this may be better as an example:
```
source ~/.bash-preexec.sh
preexec() { if echo "$1" | egrep -q "^ls$" ; then return 1 ; fi ; }
shopt -s extdebug
ls -al
ls
```

This disables the "ls" command, but allows "ls -al" to work.

**Comment by rcaloras** [comment]
@richard-scott Thanks for the example! :+1: 
@frozenminds going to close this out as Rich's example looks sufficient. Feel free to reopen or start a new issue if you have any other questions/problems.
