### ISSUE TITLE
support required for logging mysql shell using pre-exec

### ISSUE THREAD

**Issue by aravindananthapadmanabhan** [rcaloras/bash-preexec#45]
I Think it will be a nice feature to have  a method of supporting logs of mysql queries fired from a mysql shell.

**Comment by rcaloras** [comment]
Cool idea. I've always wanted to pull shell/console commands for things like MySql, Postgres, Mongo or REPLs (e.g. Python, Scala, Ruby consoles) into a service like [Bashhub](https://bashhub.com). 

The MySql shell is separate/different from Bash though. It's outside the scope of this project.

 I'd search around. I'm surprised a mysql shell wouldn't have this. Maybe ask over at https://github.com/mysql/mysql-shell.
