### ISSUE TITLE
Use `builtin history` instead of `history`

### ISSUE THREAD

**Issue by gnachman** [rcaloras/bash-preexec#55]
Some users like to redefine bash builtins, so it's unsafe to use them without saying `builtin` first. Here's an issue report where a user had defined an alias for `history` and it broke `bash-preexec`: https://gitlab.com/gnachman/iterm2/issues/6063

What do you think about replacing the use of `history` with `builtin history`?

**Comment by D630** [comment]
Yeah.

Or `command \history`.

> Some users like to redefine bash builtins, so it's unsafe to use them without saying builtin first.

Cons: It slows down everything a bit, and you need to take care of quoting in combination with some builtins.

And what about:
```sh
alias builtin='echo alias'; function builtin { echo func; };
```

**Comment by rcaloras** [comment]
@gnachman sgtm. 
@D630 The cons you listed apply to adding builtin here?

Stamp #56 if you think we're good to go and I'll merge and tag :+1:

**Comment by rcaloras** [comment]
Cut [0.3.4](https://github.com/rcaloras/bash-preexec/releases/tag/0.3.4). @gnachman thanks for reporting.
