### ISSUE TITLE
Incompatible prompt_command settings

### ISSUE THREAD

**Issue by jombooth** [rcaloras/bash-preexec#58]
Some users of a project I work on that's based on Bash-Preexec modify their prompt command in ~/.bashrc after sourcing the script. In some cases, we've found they'll do this:

<source bash-preexec>
PROMPT_COMMAND+="history -a"

This breaks BP, because prompt_command ends in "__bp_install", so on first execution, the user gets a
"no such command: __bp_installhistory" message.

To fix this particular issue, I suggest wrapping the prompt_command installed by bash_preexec in newlines, ie
__bp_preexec_foo_bar; __bp_install \n

so that appending to PROMPT_COMMAND won't cause problems. Newlines are in general the most universally compatible way of splitting commands in Bash, so we could consider using them wherever a problem might arise, ie,

\n __bp_preexec_foo_bar \n __bp_install \n

This way, even if someone does a PROMPT_COMMAND="echo good morning! $PROMPT_COMMAND", after sourcing bash-preexec, the result will still be correct.

w.r.t. testing this - it would be ideal to test various possible orderings of setting up custom prompt commands and sourcing Bash-Preexec, for example,

adjust PROMPT_COMMAND
source bash_preexec
adjust PROMPT_COMMAND again

source bash_preexec
adjust PROMPT_COMMAND

**Comment by rcaloras** [comment]
Yeah, there used to be semicolons, but we decided to remove them. https://github.com/rcaloras/bash-preexec/pull/41

Newlines sound more forgiving :) want to submit the PR?

**Comment by rcaloras** [comment]
@jombooth closing this guy since I merged the PR. Hoping this is fixed now on master.
