### ISSUE TITLE
Restore DEBUG trap preservation

### ISSUE THREAD

**Issue by dimo414** [rcaloras/bash-preexec#61]
PR #60 regressed the fix to #39. We need to identify a new mechanism to capture traps that avoids the issues discussed there.

As I understand it this is only an issue for users who erroneously `export` their `PROMPT_COMMAND` at some point in their `.bashrc`, so if we can detect that case we could simply not preserve traps for those users.

**Comment by lguelorget** [comment]
Gave it a go at: https://github.com/rcaloras/bash-preexec/pull/62

**Comment by lguelorget** [comment]
I believe I've addressed the regression in https://github.com/rcaloras/bash-preexec/pull/62/. Let me know if that works.

**Comment by rcaloras** [comment]
@lguelorget Thanks a lot for the PR! Much appreciated :+1: :100:

**Comment by rcaloras** [comment]
Released 0.3.6 which has the fix for this.
