### ISSUE TITLE
Pre-pend sudo to execution of binaries in /sbin

### ISSUE THREAD

**Issue by ageis** [rcaloras/bash-preexec#67]
This is more of a support question. I'm wondering if this is a valid use case:
```
 precmd() {                                                                      
     cmdpath=`which $1`                                                          
     if [[ "$cmdpath" =~ "^(/usr)?/sbin/.*" ]]; then                             
         sudo $1                                                                 
     fi                                                                          
 }     
```
If I'm running anything in /sbin (requiring root) then I'd like to prepend sudo to the command automatically.

**Comment by D630** [comment]
No, I don't think so. Function executions via the precmd-hook are associated with the primary prompt, which comes into play after the whole command line has been executed. Your function just runs the command line as normal, but `cmdpath` is always empty. Replace the body with `echo "$1"` and then you can see that precmd doesn't take an argument.

**Comment by D630** [comment]
The use of a preexec-hook for this task is really complicated, because you must work with `extdebug` (?!). Especially, when the command line is not a one-word simple command or contains command subsitution. I would rather use aliases:

```sh
for p in {/usr,}/sbin/?*;
do 
    alias ${p##*/}="sudo $p ";
done;
```

**Comment by ageis** [comment]
Okay, thanks for clarifying!

**Comment by rcaloras** [comment]
@D630 thanks for providing support. Closing, feel free to reopen if needed.

**Comment by D630** [comment]
By the way, it's easier to replace/substitute the command line using a `preread-hook` in bpx. But parsing of complicated lines is still very tricky. And there is no thing like "substitute pipeline 3, only if pipeline 2 has failed".  

Exp1:

```sh
$ shopt -u expand_aliases;
$ function preread { READLINE_LINE="ls / | head -n 1"; };
$ preread_functions=(preread);
$ ls
bin
$ history 2
 4  ls / | head -n 1
 5  history 2
```

Exp2:

```sh
$ unalias FOO;
$ alias 'ls=ls -1'
$ function preread { READLINE_LINE=${rl0//FOO/"ls / | head -n 1"}; }
$ preread_functions=(preread);
$ echo; FOO; echo; echo $(FOO)

bin

bin
$ history 2
 4  echo; ls / | head -n 1; echo; echo $(ls / | head -n 1)
 5  history 2
```

Exp3:

```sh
$ alias 'ls=/bin/ls / | head -n 1';
$ unalias head;
$ function preread { __bpx_set_rl2; READLINE_LINE=${rl2[@]}; };
$ preread_functions=(preread);
$ ls; ls && ls
bin
bin
bin
$ history 2
 4  /bin/ls -1 / | head -n 1; /bin/ls -1 / | head -n 1 && /bin/ls -1 / | head -n 1
 5  history 2
```

**Comment by Arinerron** [comment]
For others who are working on this and want a bash + zsh solution, I wrote this ugly hack based on @d630's first message:

```sh
for x in $(echo "$PATH" | tr ':' ' '); do
  for p in $x/?*; do
    name="${p##*/}"
    alias "$name"="echo $name"
  done
done
```

Example:

```
[~] echo hello world
echo hello world
[~] whoami
echo whoami
[~] id
echo id
[~] echo "this is a test"
echo this is a test
[~] printf "%s" "asdf"
echo printf %s asdf
```

In a way it works?
