### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by DevasiaThomas** [rcaloras/bash-preexec#68]
Hi,
I sent @rcaloras and email (the one on github). Its about something I am working on and is very close in its implementation to this project.

**Comment by rcaloras** [comment]
Hey @DevasiaThomas saw your message about changing commands with bash-preexec. I don't believe there's an easy way to do this. You could capture a command and run a modified version in preexec, but there's not a good way to substitute your modified version. 

See this recent similar question: https://github.com/rcaloras/bash-preexec/issues/67

**Comment by rcaloras** [comment]
Thanks for reaching out! Closing this as I don't believe bash-preexec supports your use case.

**Comment by DevasiaThomas** [comment]
Thanks for answering. I kinda figured it out... but I'm stuck with [this issue with respect to non interactive shells] (https://stackoverflow.com/questions/48672149/im-trying-to-prevent-the-execution-of-a-command-in-bash-doesnt-work-always)
