### ISSUE TITLE
Instructions inconsistent with script comments

### ISSUE THREAD

**Issue by jamesderlin** [rcaloras/bash-preexec#71]
The project `README.md` clearly states:

> It must be the last thing imported in your bash profile.

`bash-preexec.sh` itself states:

> Sets our trap and __bp_install as part of our PROMPT_COMMAND to install
> after our session has started. This allows bash-preexec to be inlucded
> at any point in our bash profile.

This comment (which has a typo) seems to contradict the instructions from `README.md`.

The `README.md` instructions seem more correct; if `bash-preexec.sh` is not last, any subsequent changes to `PROMPT_COMMAND` will be lost.  At the very least, the script comment is misleading.

Additionally, perhaps `bash-preexec.sh` could emit a warning if `PROMPT_COMMAND` has been modified between `__bp_install_after_session_init()` and  `__bp_install()`? (I spent a while trying to figure out why https://github.com/rupa/z wasn't working on a system where an administrator (unbeknownst to me) included `bash-preexec.sh` via a chain of inclusions starting from `/etc/bash.bashrc`.)

**Comment by rcaloras** [comment]
@jamesderlin Thanks for the feedback and opening the issue. Sorry it caused an issue with `z` not working properly. We should be able to preserve the altered `PROMPT_COMMAND` during `__bp_install`, but I'm not positive. I'll take a look this weekend. Please feel free to submit a PR if you think you have a fix.

**Comment by rcaloras** [comment]
Investigated this a bit more. Looks like the preservation of `PROMPT_COMMAND` was altered in https://github.com/rcaloras/bash-preexec/issues/39. Going to reopen that issue to see if we can keep it preserved.

**Comment by rcaloras** [comment]
This should be fixed in 0.4.0 since #39 is now fixed. Closing out.
