### ISSUE TITLE
Can you cancel a command based on logic within preexec?

### ISSUE THREAD

**Issue by adamtaylor13** [rcaloras/bash-preexec#75]
Hey guys,

Sorry if this already exists as an issue / question. I did some googling and read through the issues where and couldn't find a confirmation one way or another.

One thing that I'd like to do is possibly cancel a command altogether if some certain critera is met.
For example, I tried to run `git push` and hadn't run my linter yet, then I want it to break and not actually run git push.

Is there any way to handle this within preexec? It looked like the answer _might_ be to hack something around your history and/or traps?

![image](https://user-images.githubusercontent.com/2922753/48031988-9e3d8a80-e11b-11e8-8b8f-a91034958c6d.png)

Thanks in advance for any advice on this!

**Comment by d630** [comment]
Hey,

IMO, too complicated, unfortunately! I suppose, that's what git hooks are for. If not, you can also use shell aliases, shell functions, or simple wrapper scripts for such things

**Comment by rcaloras** [comment]
Hi @adamtaylor13, agree with @d630. The easiest way to do this is probably with some aliases or wrappers.
