### ISSUE TITLE
Install fails when bash is in POSIX mode

### ISSUE THREAD

**Issue by mohd-akram** [rcaloras/bash-preexec#92]
I run my bash in POSIX mode and noticed that the install step fails due to how `trap` is used (see [Bash POSIX Mode](https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html)).

To fix it, I did something like this:

```bash
case :$SHELLOPTS: in *:posix:*) posix=1;; esac
if [ "$posix" ]; then pre="set +o posix"; post="set -o posix"; fi
. bash-preexec.sh
PROMPT_COMMAND="$pre
$PROMPT_COMMAND
$post"
```

Maybe it would be useful to incorporate this into the script.

**Comment by dimo414** [comment]
This should be fixed now, see #106.

That said, POSIX-compatibility is hard to maintain, and shouldn't be expected of a project that doesn't commit to doing so. If you choose to run your shell in POSIX mode you should expect that numerous "standard" Bash features, and libraries that depend on those features, will not work.

**Comment by gitwdel** [comment]
Install fails when bash is in POSIX mode #92

**Comment by rcaloras** [comment]
@mohd-akram can you confirm latest master fixes this? Closing feel free to reopen otherwise.
