### ISSUE TITLE
Is it possible to abort several simple commands typed into the command line altogether?

### ISSUE THREAD

**Issue by stevepp** [rcaloras/bash-preexec#93]
As shown in # 37, enabling extdebug using the shopt utility and return a non-zero status from the preexec function would cause the next simple command to be skipped. Is it possible to abort several simple commands typed into the command line altogether, which are separated by the control operators such as ";"?

For example, if I typed "uptime; df -h", the first command "uptime" is skipped. However, "df -h" still gets executed. Is it possible to also skip the second simple command?

**Comment by werg** [comment]
I'm dealing with the same issue. @stevepp  did you find a workaround?

**Comment by rcaloras** [comment]
I don't believe there's a way to do this. Closing.
