### ISSUE TITLE
bash-preexec steps on `var`

### ISSUE THREAD

**Issue by gnachman** [rcaloras/bash-preexec#95]
At this line:

https://github.com/rcaloras/bash-preexec/blob/9811ba8b7694cdbd9debed931e922b67e439197a/bash-preexec.sh#L56

Should be preceded by `local var`. I received a downstream pull request from a user:

https://github.com/gnachman/iterm2-website/pull/64

**Comment by rcaloras** [comment]
should now be fixed on master. Closing.
